FROM eclipse-temurin:17-jdk-jammy


WORKDIR /doctordb
COPY . /doctordb/
USER root
CMD ["chown", "-R", "/doctordb"]

RUN chmod +X /doctordb/gradlew
CMD ["/doctordb/gradlew", "clean", "build", "jar"]

EXPOSE 8081/tcp
CMD ["java", "-jar", "/doctordb/build/libs/userdb-0.0.1-SNAPSHOT.jar"]