FROM eclipse-temurin:17-jdk-jammy


WORKDIR /userdb
COPY . /userdb/
USER root
CMD ["chown", "-R", "/userdb"]

RUN chmod +X /userdb/gradlew
CMD ["/userdb/gradlew", "clean", "build", "jar"]

EXPOSE 8081/tcp
CMD ["java", "-jar", "/userdb/build/libs/userdb-0.0.1-SNAPSHOT.jar"]