FROM eclipse-temurin:17-jdk-jammy


WORKDIR /analytics
COPY . /analytics/
USER root
CMD ["chown", "-R", "/analytics"]

RUN chmod +X /userdb/gradlew
CMD ["/analytics/gradlew", "clean", "build", "jar"]

EXPOSE 8081/tcp
CMD ["java", "-jar", "/userdb/build/libs/analytics-0.0.1-SNAPSHOT.jar"]