# Use root/example as user/password credentials
version: '3.1'

services:
  mediscreen-doctordb-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  mediscreen-doctordb-app:
    build:
      context: ../
      dockerfile: DockerFile
    container_name: mediscreen-doctordb-app
    ports:
      - "8081:8081"
    environment:
      - DB_SERVER=mediscreen-doctordb-db
      - SECRET=root
    links:
      - mediscreen-doctordb-db